#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun  4 12:42:09 2026
@author: jonah
"""

from pathlib import Path
from datetime import datetime
import os
import stat

def generate_batch_deploy_script(
    batch_data: list,
    output_script_path: Path
):
    """
    Generates a SINGLE .sh script to deploy multiple prepared sequences using
    a two-stage transfer (Local -> Proxy -> Scanner) to keep SSH keys isolated.
    """
    proxy_host = "scannersub"
    scanner_target = "sdc@ucsfmb3tmr"

    # Build the dynamic deployment steps for the bash script
    deployment_steps = []
    for item in batch_data:
        # We need the basename of the files/folders to reference them on the proxy
        item_name = item['local_path'].name
        item_id = item['item_id']
        
        deployment_steps.append(f"""
echo "--------------------------------------------------"
echo "Deploying: {item_name}"
echo "--------------------------------------------------"

echo "1. Staging files on proxy ($PROXY_HOST)..."
ssh $SSH_OPT "$PROXY_HOST" "mkdir -p \\"$PROXY_TMP_DIR/{item_id}\\""

scp $SCP_OPT -r "{item['local_path']}" "$PROXY_HOST:$PROXY_TMP_DIR/{item_id}/"

echo "2. Pushing from proxy to scanner ($SCANNER_TARGET)..."
# This command runs ON the proxy, utilizing the SSH keys stored there
ssh $SSH_OPT "$PROXY_HOST" "scp -r \\"$PROXY_TMP_DIR/{item_id}/{item_name}\\" \\"$SCANNER_TARGET:{item['remote_dir']}\\""
""")

    steps_joined = "\n".join(deployment_steps)

    script_content = f"""#!/bin/bash
#
# This script was auto-generated by prep_pge2.py
# It deploys a batch of {len(batch_data)} items via a secure TWO-STAGE copy.
# Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
#

set -e

# --- Configuration ---
PROXY_HOST="{proxy_host}"
SCANNER_TARGET="{scanner_target}"

# Generate unique temp paths using the script's Process ID ($$)
SOCKET="/tmp/pge2_deploy_socket_$$"
PROXY_TMP_DIR="/tmp/pge2_staging_$$"

echo "--- Starting Secure TWO-STAGE pge2 Deployment ({len(batch_data)} items) ---"
echo "Route: Home -> $PROXY_HOST (Staging) -> $SCANNER_TARGET"
echo ""
echo "🔑 Opening master connection. Please complete your 2FA for $PROXY_HOST..."

# 1. Establish Master Connection (No -J jump flag, just a direct connection to proxy)
ssh -M -S "$SOCKET" -f -N "$PROXY_HOST"

# 2. Safety Cleanup
# Ensures the staging folder is wiped and the background socket is closed on exit
trap 'echo -e "\\n🧹 Cleaning up staging files on $PROXY_HOST..."; ssh -S "$SOCKET" "$PROXY_HOST" "rm -rf \\"$PROXY_TMP_DIR\\""; echo "🧹 Closing master SSH connection..."; ssh -S "$SOCKET" -O exit "$PROXY_HOST" 2>/dev/null' EXIT

# 3. Configure SCP and SSH to use the established socket
SCP_OPT="-o ControlPath=$SOCKET"
SSH_OPT="-o ControlPath=$SOCKET"

echo "✅ Connection established. Preparing staging area..."
ssh $SSH_OPT "$PROXY_HOST" "mkdir -p \\"$PROXY_TMP_DIR\\""

# --- Deployment Steps ---
{steps_joined}

echo
echo "=== All {len(batch_data)} items successfully deployed! ==="
exit 0
"""
    try:
        output_script_path.write_text(script_content)
        st = os.stat(output_script_path)
        os.chmod(output_script_path, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        print(f"\n[Success] Generated master deploy script: '{output_script_path}'")
    except Exception as e:
        print(f"Error generating master deploy script: {e}")


def prep_pge2_batch(batch_tasks: list, scanner_sequence_dir: Path, scanner_entry_dir: Path, output_script_path: Path):
    """
    Processes a batch of sequence files, creates .entry files, and consolidates 
    everything into a single deployment manifest.
    
    batch_tasks format: [{"seq_path": Path, "pge_n": int}, ...]
    """
    batch_manifest = []

    for task in batch_tasks:
        seq_filename = task["seq_path"]
        pge_n = task.get("pge_n", 60) # Fallback to 60 if not provided
        
        if not isinstance(seq_filename, Path):
            seq_filename = Path(seq_filename)

        # 1. Target the .pge directory directly
        pge_local_path = seq_filename.with_suffix('.pge').resolve()
        seq_name = seq_filename.stem

        # 2. Create the .entry file locally
        entry_filename = f"pge{pge_n}.entry"
        # Add .resolve() here to guarantee an absolute path in the bash script
        entry_local_path = (seq_filename.parent / entry_filename).resolve()
        
        # Build the exact scanner string format
        # Force forward slashes for the Linux scanner environment
        remote_pge_path = f"{scanner_sequence_dir.as_posix()}/{pge_local_path.name}"
        entry_content = f"1\n{remote_pge_path}\n\n"
        
        entry_local_path.write_text(entry_content)

        # 3. Append the .pge sequence directory to manifest
        batch_manifest.append({
            "local_path": pge_local_path,
            "remote_dir": scanner_sequence_dir,
            "item_id": f"{seq_name}_pge",
        })
        
        # 4. Append the .entry file to manifest
        batch_manifest.append({
            "local_path": entry_local_path,
            "remote_dir": scanner_entry_dir,
            "item_id": f"{seq_name}_entry",
        })

    # Generate ONE master deployment script for all sequences and entries combined
    if batch_manifest:
        generate_batch_deploy_script(batch_manifest, output_script_path)